# Generated by Django 4.1 on 2022-08-31 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.TimeField(default=datetime.time(0, 0))),
                ('hour_end', models.TimeField(default=datetime.time(23, 59, 59))),
            ],
            options={
                'verbose_name_plural': 'hours available',
                'ordering': ['hour_start'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_num', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
            ],
            options={
                'ordering': ['month_num'],
            },
        ),
        migrations.CreateModel(
            name='ShadowSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'tiny'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('LT', 'long & thin'), ('XL', 'very large'), ('XLF', 'very large (finned)'), ('XXL', 'huge')], default='XS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DiveFish',
            fields=[
                ('idd', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('movement', models.CharField(choices=[('ST', 'stationary'), ('SL-', 'very slow'), ('SL', 'slow'), ('M', 'medium'), ('F', 'fast'), ('F+', 'very fast')], max_length=15)),
                ('catches_req', models.IntegerField(default=0, verbose_name='df catches required')),
                ('hours', models.ManyToManyField(blank=True, to='carousel.hours')),
                ('month', models.ManyToManyField(blank=True, to='carousel.month')),
                ('size', models.ManyToManyField(blank=True, to='carousel.shadowsize')),
            ],
            options={
                'verbose_name_plural': 'DiveFish',
            },
        ),
    ]
