# Generated by Django 4.1 on 2022-09-01 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_rename_idd_divefish_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divefish',
            options={'ordering': ['id'], 'verbose_name_plural': 'DiveFish'},
        ),
        migrations.RemoveField(
            model_name='divefish',
            name='hours',
        ),
        migrations.AddField(
            model_name='divefish',
            name='interval_end',
            field=models.TimeField(default=datetime.time(23, 59, 59, 999999)),
        ),
        migrations.AddField(
            model_name='divefish',
            name='interval_start',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.RemoveField(
            model_name='divefish',
            name='size',
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
        migrations.DeleteModel(
            name='ShadowSize',
        ),
        migrations.AddField(
            model_name='divefish',
            name='size',
            field=models.CharField(choices=[('XS', 'tiny'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('LT', 'long & thin'), ('XL', 'very large'), ('XLF', 'very large (finned)'), ('XXL', 'huge')], default='XS', max_length=20),
        ),
    ]
