# Generated by Django 4.1 on 2022-09-01 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0003_alter_divefish_options_remove_divefish_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divefish',
            name='interval2_end',
            field=models.TimeField(default=datetime.time(23, 59, 59, 999999)),
        ),
        migrations.AddField(
            model_name='divefish',
            name='interval2_start',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
