# Generated by Django 4.1 on 2022-09-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0004_divefish_interval2_end_divefish_interval2_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divefish',
            name='month',
            field=models.ManyToManyField(blank=True, null=True, to='carousel.month'),
        ),
    ]
