# Generated by Django 4.1 on 2022-09-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0005_alter_divefish_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divefish',
            name='month',
            field=models.ManyToManyField(blank=True, to='carousel.month'),
        ),
    ]
