# Generated by Django 4.1 on 2022-09-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0006_alter_divefish_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divefish',
            options={'ordering': ['name'], 'verbose_name_plural': 'DiveFish'},
        ),
    ]
