# Generated by Django 4.1 on 2022-09-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0007_alter_divefish_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divefish',
            options={'ordering': [], 'verbose_name_plural': 'DiveFish'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={},
        ),
    ]
