# Generated by Django 4.1 on 2022-09-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0008_alter_divefish_options_alter_month_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divefish',
            options={'ordering': ['id'], 'verbose_name_plural': 'DiveFish'},
        ),
    ]
