# Generated by Django 4.1 on 2022-09-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0009_alter_divefish_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divefish',
            options={'ordering': ['name'], 'verbose_name_plural': 'DiveFish'},
        ),
    ]
