# Generated by Django 4.1 on 2022-09-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0011_fish_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='location',
            field=models.CharField(blank=True, choices=[('DISGBEACH', 'disguised on shoreline'), ('DISGTREE', 'disguised under trees'), ('FLY', 'flying'), ('FLYBPBFLOWER', 'flying near blue/purple/black flowers'), ('FLYFLOWER', 'flying near flowers'), ('LIGHT', 'flying near light sources'), ('TRASHTURNIP', 'flying near trash/rotten turnips'), ('NEARWATER', 'flying near water'), ('HITROCK', 'from hitting rocks'), ('BEACHROCK', 'on beach rocks'), ('FLOWER', 'on flowers'), ('PALM', 'on palm trees'), ('RIVERPOND', 'on rivers/ponds'), ('ROCKBUSH', 'on rocks/bushes'), ('TURNIPCANDYLOLLI', 'on rotten turnips/candy/lollipops'), ('GROUND', 'on ground'), ('STUMP', 'on tree stumps'), ('TREE', 'on trees'), ('TREEHC', 'on trees (hardwood/cedar)'), ('VILL', 'on villagers'), ('WFLOWER', 'on white flowers'), ('SNOW', 'pushing snowballs'), ('SHAKE', 'shaking trees'), ('SHAKEHC', 'shaking trees (hardwood/cedar)'), ('UNDER', 'underground')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='bug',
            name='weather',
            field=models.CharField(choices=[('A', 'Any weather'), ('R', 'Rain only'), ('A-R', 'Any weather except Rain')], default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='fish',
            name='location',
            field=models.CharField(blank=True, choices=[('PI', 'pier'), ('PO', 'pond'), ('R', 'river'), ('RC', 'river (clifftop)'), ('RM', 'river (mouth)'), ('S', 'sea')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='fish',
            name='weather',
            field=models.CharField(choices=[('A', 'Any weather'), ('R', 'Rain only')], default='A', max_length=20),
        ),
    ]
