# Generated by Django 4.1 on 2022-09-02 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0012_bug_location_bug_weather_fish_location_fish_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='interval2_end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='divefish',
            name='interval2_end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='fish',
            name='interval2_end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
