# Generated by Django 4.1 on 2022-09-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0013_alter_bug_interval2_end_alter_divefish_interval2_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='location',
            field=models.CharField(blank=True, choices=[('DISGBEACH', 'disguised on shorelines'), ('DISGTREE', 'disguised under trees'), ('FLY', 'flying'), ('FLYBPBFLOWER', 'flying near blue, purple & black flowers'), ('FLYFLOWER', 'flying near flowers'), ('LIGHT', 'flying near light sources'), ('TRASHTURNIP', 'flying near trash & rotten turnips'), ('NEARWATER', 'flying near water'), ('HITROCK', 'falls from rocks being hit'), ('BEACHROCK', 'on beach rocks'), ('FLOWER', 'on flowers'), ('PALM', 'on palm trees'), ('RIVERPOND', 'on rivers & ponds'), ('ROCKBUSH', 'on rocks & bushes'), ('TURNIPCANDYLOLLI', 'on rotten turnips, candy & lollipops'), ('GROUND', 'on ground'), ('STUMP', 'on tree stumps'), ('TREE', 'on trees'), ('TREEHC', 'on hardwood & cedar trees'), ('VILL', 'on villagers'), ('WFLOWER', 'on white flowers'), ('SNOW', 'pushing snowballs'), ('SHAKE', 'falls from shaking trees'), ('SHAKEHC', 'shaking hardwood & cedar trees'), ('UNDER', 'underground')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='bug',
            name='weather',
            field=models.CharField(choices=[('A', 'any weather'), ('R', 'rain only'), ('A-R', 'any weather except rain')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='divefish',
            name='size',
            field=models.CharField(choices=[('XS', 'tiny'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('LT', 'long & thin'), ('XL', 'very large'), ('XLF', 'very large with fin'), ('XXL', 'huge')], default='XS', max_length=20),
        ),
        migrations.AlterField(
            model_name='fish',
            name='location',
            field=models.CharField(blank=True, choices=[('PI', 'pier'), ('PO', 'pond'), ('R', 'river'), ('RC', 'river clifftop'), ('RM', 'river mouth'), ('S', 'sea')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='fish',
            name='size',
            field=models.CharField(choices=[('XS', 'tiny'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('LT', 'long & thin'), ('XL', 'very large'), ('XLF', 'very large with fin'), ('XXL', 'huge')], default='XS', max_length=20),
        ),
        migrations.AlterField(
            model_name='fish',
            name='weather',
            field=models.CharField(choices=[('A', 'any weather'), ('R', 'rain only')], default='A', max_length=20),
        ),
    ]
