# Generated by Django 4.1 on 2022-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0014_alter_bug_location_alter_bug_weather_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gyroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name missing', max_length=20)),
                ('style', models.CharField(default='style missing', max_length=100)),
                ('color1', models.CharField(default='color1 missing', max_length=20)),
                ('color2', models.CharField(default='color2 missing', max_length=20)),
            ],
        ),
    ]
