# Generated by Django 4.1 on 2022-09-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0015_gyroid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gyroid',
            options={'ordering': ['name', 'style']},
        ),
    ]
