# Generated by Django 4.1 on 2022-09-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0016_alter_gyroid_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FilePathField(default='Gyroid_NH_Inv_Icon.png', path='static/carousel/other images/Category_New Horizons gyroid icons - Animal Crossing Wiki - Nookipedia_files')),
            ],
        ),
    ]
