# Generated by Django 4.1 on 2022-09-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0017_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FilePathField(default='Gyroid_NH_Inv_Icon.png', path='C:/Users/schul/Category_New Horizons gyroid icons - Animal Crossing Wiki - Nookipedia_files'),
        ),
    ]
