# Generated by Django 4.1 on 2022-09-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0018_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FilePathField(default='C:\\Users\\schul\\WebDev\\critterticker/carousel/static/carousel/other images/Gyroid_NH_Inv_Icon.png', path='C:\\Users\\schul\\WebDev\\critterticker/carousel/static/carousel/gyroid icons'),
        ),
    ]
