# Generated by Django 4.1 on 2022-09-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0019_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='filepath',
        ),
    ]
